server:
  port: 8999

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update    # ??? ?? ???? ??
    properties:
      hibernate:
        validator:
          apply_to_ddl: false  # DDL ?? ?? ??? ?? ?? ??
        highlight: true   # ?? ????? ??
        show_sql: true    # ?? ?? ?? ??
        format_sql: true  # ?? ??? ?? -> SQL ?? ?? ??
  h2:
    console:
      enabled: true       # H2 ?? ???
      path: /h2-console    # H2 ?? ?? ??
  datasource:
    url: jdbc:h2:~/h2_db/test
    username: sa
    password:
    driver-class-name: org.h2.Driver